export const CHANGE_SEARCH = 'CHANGE_SEARCH';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_NOTES_START = 'GET_NOTES_START';
export const GET_NOTES_SUCCESS = 'GET_NOTES_SUCCESS';
export const GET_NOTES_FAIL = 'GET_NOTES_FAIL';
